name: CI Build & Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    
    steps:
      - uses: actions/checkout@v2
      
      - name: JDK 8
        uses: actions/setup-java@v4
        with: 
          java-version: 8
          distribution: 'temurin'
          
      - name: Maven Build & Test
        run: mvn -f com.shemilikevin.app.tracker/pom.xml clean verify