name: CI Build & Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      workdir: com.shemilikevin.app.tracker

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: 8
        distribution: 'temurin'

    - name: Cache Maven Packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2-

    - name: Enable Coveralls (Internal PR or Push)
      if: ${{ env.COVERALLS_REPO_TOKEN }}
      run: echo "PROFILE=-Pcoveralls" >> $GITHUB_ENV

    - name: Maven Build & Test
      run: xvfb-run mvn verify $PROFILE
      working-directory: ${{ env.workdir }}

    - name: Generate JUnit Report
      run: |
        mvn surefire-report:report-only \
        surefire-report:failsafe-report-only
      working-directory: ${{ env.workdir }}

    - name: Archive JUnit Report
      uses: actions/upload-artifact@v4
      with:
        name: surefire-report
        path: '**/target/reports'