name: Mutation Testing

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      workdir: com.shemilikevin.app.tracker

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: 8
        distribution: 'temurin'

    - name: Cache Maven Packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2-

    - name: Maven Build & Test
      run: mvn verify -Ppit-tests
      working-directory: ${{ env.workdir }}

    - name: Archive PIT Report
      uses: actions/upload-artifact@v4
      with:
        name: pit-reports
        path: '**/target/pit-reports'